spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/BobrAITest  # Изменить на свое имя базы данных
    username: radik                                   # Изменить на свое имя пользователя в PostgreSQL
    password: radik                                   # Изменить на свой пароль пользователя в PostgreSQL
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    cache-names: weather
    caffeine:
      spec: maximumSize=500, expireAfterWrite=10m
  main:
    allow-bean-definition-overriding: true
    web:
      whitelabel:
        enabled: false
  openapi:
    enabled: true

telegram:
  bot:
    username: radik_bobrai_test_bot
    token: "7645426104:AAHu7CadIun3xQYamS7AhkUZt4fo3e9d3Sc"

logging:
  file:
    name: logs/app.log
  level:
    org.telegram: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080